services:
  anicroche:
    build: ./anicroche
    container_name: anicroche
    ports:
      - "4035:4035"
    environment:
      - PORT=4035
    volumes:
      - ./anicroche/avec.js:/app/avec.js
      - ./anicroche/adn:/app/adn
