services:
  anicroche:
    build: ./anicroche
    container_name: anicroche
    ports:
      - "4025:4025"
    environment:
      - PORT=4025
    volumes:
      - ./anicroche/avec.js:/app/avec.js
      - ./anicroche/adn:/app/adn
